### ISSUE TITLE
Placing 2 buttons in the same horizontal line, not vertical

### ISSUE THREAD

**Issue by evrenios** [carsonperrotti/CNPPopupController#14]
Hello, i'v been trying to put 2 button in the same line, like made in UIAlertView, which contains 2 button. How can i accomplish this ?  Thanks in advance.

**Comment by carsonperrotti** [comment]
Sorry for the long delay, my day job has taken up most of my time. I am pushing a release tonight that supports custom views.

**Comment by carlosfer02** [comment]
Hello, is this feature already out? i am trying to show 2 button in the same row but i cant.

**Comment by carsonperrotti** [comment]
Version 0.2.0 has been released and has support for UIViews. Check it out.
