### ISSUE TITLE
Add Ability to use a UITextField

### ISSUE THREAD

**Issue by jeremytrains** [carsonperrotti/CNPPopupController#17]
It would be awesome if a UITextField could be used (the contents array could be NSAttributedString, UIImage, or UITextField) so that user input can be received. I love the style of this popup and would like to use this library for all of my alerts, not just ones that don't have text input. Thanks!

**Comment by carsonperrotti** [comment]
Adding custom view support in version 0.2.0 which I will release tonight.

**Comment by kishorehvk** [comment]
is there any validation methods for uitextfield in cnppopupcontroller
