### ISSUE TITLE
Incompatibility with Pushwoosh frameworks

### ISSUE THREAD

**Issue by zabumba69** [carsonperrotti/CNPPopupController#20]
If I simply add the frameworks Pushwoosh in my project and initialize in the appdelegate, my popup is not shown. If I remove the pushwoosh init in delegate my PopUp is displayed. Could someone help me with this problem? I love the control and would love to continue using.

Thanks in Advance!

**Comment by carsonperrotti** [comment]
I'm not sure how this would cause an incompatibility, but I'll look into it and see if I can find anything.

**Comment by zabumba69** [comment]
Thanks for your help, I love the your controller.

**Comment by carsonperrotti** [comment]
It looks like they do add their own UIWindow to handle rich push presentation. This may cause the popup controller to not present on the correct window. I am finishing up a new version of the controller that no longer relies on UIWindow for presentation. I will be pushing it very shortly.
