### ISSUE TITLE
failed CNPPopupController

### ISSUE THREAD

**Issue by braoliveSCC** [carsonperrotti/CNPPopupController#24]
Hello, Your framework is show is very easy to adapt the app, but an error message that I can not understand what could have happened:

02/21/2015 16: 49: 36,332 CalculeJá [782: 116232] Unable to Satisfy constraints simultaneously.
Probably at least one of the constraints in the Following list is one you do not want. Try this: (1) look at each constraint and try to figure October Which you do not expect; (2) find the code que added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints That You do not understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint: 0x14ec06f0 h = v = --- --- V: [UIWindow: 0x14e61c40 (0)]>",
    "<NSLayoutConstraint: 0x16749530 V | - (0) - [UIView: 0x16725c30] (Names: '|': UIWindow: 0x14e61c40)>"
    "<NSLayoutConstraint: 0x16738a60 UIView: 0x16725c30.bottom == UIWindow: 0x14e61c40.bottom>"
    "<NSLayoutConstraint: 0x14d05ef0 V | - (16) - [UILabel: 0x14db3cb0'ATEN \ U00c7 \ U00c3O! '] (Names:' | ': UIView: 0x1674c760)>"
    "<NSLayoutConstraint: 0x16751d50 V: [UILabel: 0x14db3cb0'ATEN \ U00c7 \ U00c3O! '] - (12) - [UILabel: 0x14d197d0'Deslize left to ..."]> ",
    "<NSLayoutConstraint: 0x16743970 V: [UILabel: 0x14d197d0'Deslize left for ... '] - (12) - [UIImageView: 0x167498b0]>",
    "<NSLayoutConstraint: 0x16720e40 V: [UIImageView: 0x167498b0] - (12) - [UILabel: 0x14d19000'Sobre the screen to return ']>"
    "<NSLayoutConstraint: 0x14df65b0 V: [UILabel: 0x14d19000'Sobre the screen to return '] - (12) - [CNPPopupButton: 0x16755190'OK']>"
    "<NSLayoutConstraint: 0x16725b00 CNPPopupButton: 0x16755190'OK'.bottom == UIView: 0x1674c760.bottom - 16>"
    "<NSLayoutConstraint: 0x167459f0 V: [CNPPopupButton: 0x16755190'OK '(50)]>",
    "<NSLayoutConstraint: 0x16748a20 UIView: 0x1674c760.height <= UIView: 0x16725c30.height>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint: 0x14df65b0 V: [UILabel: 0x14d19000'Sobre the screen to return '] - (12) - [CNPPopupButton: 0x16755190'OK']>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the category UIConstraintBasedLayoutDebugging on UIView listed in <UIKit / UIView.h> may be helpful Also.
02/21/2015 16: 49: 36,336 CalculeJá [782: 116232] Unable to Satisfy constraints simultaneously.
Probably at least one of the constraints in the Following list is one you do not want. Try this: (1) look at each constraint and try to figure October Which you do not expect; (2) find the code que added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints That You do not understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint: 0x14ec06c0 h = v = --- --- H: [UIWindow: 0x14e61c40 (0)]>",
    "<NSLayoutConstraint: 0x14d90dd0 H | - (0) - [UIView: 0x16725c30] (LTR) (Names '|': UIWindow: 0x14e61c40)>",
    "<NSLayoutConstraint: 0x1674e3c0 UIView: 0x16725c30.right == UIWindow: 0x14e61c40.right>"
    "<NSLayoutConstraint: 0x14df44a0 H | - (16) - [UILabel: 0x14db3cb0'ATEN \ U00c7 \ U00c3O! '] (LTR) (Names' |': UIView: 0x1674c760)>",
    "<NSLayoutConstraint: 0x16751630 UILabel: 0x14db3cb0'ATEN \ U00c7 \ U00c3O 'right == UIView:. 0x1674c760.right - 16>"
    "<NSLayoutConstraint: 0x167210c0 UIView: 0x1674c760.width <= UIView: 0x16725c30.width>"
)

Will attempt to recover by breaking constraint
<!. NSLayoutConstraint: 0x16751630 UILabel: 0x14db3cb0'ATENÇÃO 'right == UIView: 0x1674c760.right - 16>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the category UIConstraintBasedLayoutDebugging on UIView listed in <UIKit / UIView.h> may be helpful Also.
02/21/2015 16: 49: 36,341 CalculeJá [782: 116232] Unable to Satisfy constraints simultaneously.
Probably at least one of the constraints in the Following list is one you do not want. Try this: (1) look at each constraint and try to figure October Which you do not expect; (2) find the code que added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints That You do not understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint: 0x14ec06c0 h = v = --- --- H: [UIWindow: 0x14e61c40 (0)]>",
    "<NSLayoutConstraint: 0x14d90dd0 H | - (0) - [UIView: 0x16725c30] (LTR) (Names '|': UIWindow: 0x14e61c40)>",
    "<NSLayoutConstraint: 0x1674e3c0 UIView: 0x16725c30.right == UIWindow: 0x14e61c40.right>"
    "<NSLayoutConstraint: 0x16720ef0 UIImageView: 0x167498b0.height <= UIImageView: 0x167498b0.width>"
    "<NSLayoutConstraint: 0x16754f70 H | - (16) - [UIImageView: 0x167498b0] (LTR) (Names '|': UIView: 0x1674c760)>",
    "<NSLayoutConstraint: 0x16754fe0 UIImageView: 0x167498b0.right == UIView: 0x1674c760.right - 16>"
    "<NSLayoutConstraint: 0x167210c0 UIView: 0x1674c760.width <= UIView: 0x16725c30.width>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint: 0x16754fe0 UIImageView: 0x167498b0.right == UIView: 0x1674c760.right - 16>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the category UIConstraintBasedLayoutDebugging on UIView listed in <UIKit / UIView.h> may be helpful Also.
02/21/2015 16: 49: 36,345 CalculeJá [782: 116232] Unable to Satisfy constraints simultaneously.
Probably at least one of the constraints in the Following list is one you do not want. Try this: (1) look at each constraint and try to figure October Which you do not expect; (2) find the code que added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints That You do not understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint: 0x14ec06c0 h = v = --- --- H: [UIWindow: 0x14e61c40 (0)]>",
    "<NSLayoutConstraint: 0x14d90dd0 H | - (0) - [UIView: 0x16725c30] (LTR) (Names '|': UIWindow: 0x14e61c40)>",
    "<NSLayoutConstraint: 0x1674e3c0 UIView: 0x16725c30.right == UIWindow: 0x14e61c40.right>"
    "<NSLayoutConstraint: 0x1672c960 H: | - (16) - [UILabel: 0x14d19000'Sobre the screen to return '] (LTR) (Names,' | ': UIView: 0x1674c760)>"
    "<NSLayoutConstraint: 0x14d174d0 UILabel: 0x14d19000'Sobre the screen to voltar'.right == UIView: 0x1674c760.right - 16>"
    "<NSLayoutConstraint: 0x167210c0 UIView: 0x1674c760.width <= UIView: 0x16725c30.width>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint: 0x14d174d0 UILabel: 0x14d19000'Sobre the screen to voltar'.right == UIView: 0x1674c760.right - 16>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the category UIConstraintBasedLayoutDebugging on UIView listed in <UIKit / UIView.h> may be helpful Also.
02/21/2015 16: 49: 36,349 CalculeJá [782: 116232] Unable to Satisfy constraints simultaneously.
Probably at least one of the constraints in the Following list is one you do not want. Try this: (1) look at each constraint and try to figure October Which you do not expect; (2) find the code que added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints That You do not understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint: 0x14ec06c0 h = v = --- --- H: [UIWindow: 0x14e61c40 (0)]>",
    "<NSLayoutConstraint: 0x14d90dd0 H | - (0) - [UIView: 0x16725c30] (LTR) (Names '|': UIWindow: 0x14e61c40)>",
    "<NSLayoutConstraint: 0x1674e3c0 UIView: 0x16725c30.right == UIWindow: 0x14e61c40.right>"
    "<NSLayoutConstraint: 0x16729040 H | - (16) - [UILabel: 0x14d197d0'Deslize left for ... '] (LTR) (Names' |': UIView: 0x1674c760)>",
    "<NSLayoutConstraint: 0x167442c0 UILabel: 0x14d197d0'Deslize from left ... 'right == UIView:. 0x1674c760.right - 16>"
    "<NSLayoutConstraint: 0x167210c0 UIView: 0x1674c760.width <= UIView: 0x16725c30.width>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint: 0x167442c0 UILabel: 0x14d197d0'Deslize from left ... 'right == UIView: 0x1674c760.right - 16.>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the category UIConstraintBasedLayoutDebugging on UIView listed in <UIKit / UIView.h> may be helpful Also.
02/21/2015 16: 49: 36,353 CalculeJá [782: 116232] Unable to Satisfy constraints simultaneously.
Probably at least one of the constraints in the Following list is one you do not want. Try this: (1) look at each constraint and try to figure October Which you do not expect; (2) find the code que added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints That You do not understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint: 0x14ec06c0 h = v = --- --- H: [UIWindow: 0x14e61c40 (0)]>",
    "<NSLayoutConstraint: 0x14d90dd0 H | - (0) - [UIView: 0x16725c30] (LTR) (Names '|': UIWindow: 0x14e61c40)>",
    "<NSLayoutConstraint: 0x1674e3c0 UIView: 0x16725c30.right == UIWindow: 0x14e61c40.right>"
    "<NSLayoutConstraint: 0x1671f850 H | - (16) - [CNPPopupButton: 0x16755190'OK '] (LTR) (Names' |': UIView: 0x1674c760)>",
    "<NSLayoutConstraint: 0x14d00310 CNPPopupButton: 0x16755190'OK'.right == UIView: 0x1674c760.right - 16>"
    "<NSLayoutConstraint: 0x167210c0 UIView: 0x1674c760.width <= UIView: 0x16725c30.width>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint: 0x14d00310 CNPPopupButton: 0x16755190'OK'.right == UIView: 0x1674c760.right - 16>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the category UIConstraintBasedLayoutDebugging on UIView listed in <UIKit / UIView.h> may be helpful Also.
02/21/2015 16: 49: 36,358 CalculeJá [782: 116232] Unable to Satisfy constraints simultaneously.
Probably at least one of the constraints in the Following list is one you do not want. Try this: (1) look at each constraint and try to figure October Which you do not expect; (2) find the code que added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints That You do not understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints)
(
    "<NSAutoresizingMaskLayoutConstraint: 0x14ec06c0 h = v = --- --- H: [UIWindow: 0x14e61c40 (0)]>",
    "<NSLayoutConstraint: 0x14d90dd0 H | - (0) - [UIView: 0x16725c30] (LTR) (Names '|': UIWindow: 0x14e61c40)>",
    "<NSLayoutConstraint: 0x1674e3c0 UIView: 0x16725c30.right == UIWindow: 0x14e61c40.right>"
    "<NSLayoutConstraint: 0x16757fb0 UIView: 0x1674c760.width == UIView: 0x16725c30.width - 40>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint: 0x16757fb0 UIView: 0x1674c760.width == UIView: 0x16725c30.width - 40>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the category UIConstraintBasedLayoutDebugging on UIView listed in <UIKit / UIView.h> may be helpful Also.

**Comment by mabarakat** [comment]
i have the same issue.

**Comment by JakobPip** [comment]
Did any of you come up with a fix?

**Comment by codzero** [comment]
i have the same issue.

**Comment by codzero** [comment]
If I simply add the GoogleMobileAds.framework in my project and initialize (GADBannerView alloc), my popup is not shown. If I remove the (GADBannerView alloc) init my PopUp is displayed.

**Comment by braoliveSCC** [comment]
I went back to version 6.12.2 and GoogleMobileAds.framework to work, the current version (7.3.1) does not.

**Comment by cvlehe** [comment]
@braoliveSCC Thank you! Thank you! Thank you! This worked for me. I never would have figured that out.

**Comment by carsonperrotti** [comment]
Version 0.2.0 has been released and should fix this bug as well. Check it out.
