### ISSUE TITLE
Does it support arbitrary UIView?

### ISSUE THREAD

**Issue by CaledoniaProject** [carsonperrotti/CNPPopupController#25]
Hi,

I'm trying to use a UIView but it seems like I can only set texts and images ... am I wrong?

**Comment by carsonperrotti** [comment]
Version 0.2.0 has been released and has support for UIViews. Check it out.

**Comment by CaledoniaProject** [comment]
Nicely done!

**Comment by carsonperrotti** [comment]
Thank you @CaledoniaProject :)
