### ISSUE TITLE
preferredPopupWidth sample implementation

### ISSUE THREAD

**Issue by sandboxdeveloper123** [carsonperrotti/CNPPopupController#27]
Hi,
I would like to ask regarding preferredPopupWidth sample implementation. I could not see in the codes on how to implement this.

Kindly help me on this as in the readme file, there is a preferredPopupWidth there.

Thanks

**Comment by judgetr** [comment]
this is what i was going to ask.Is there any update?

**Comment by judgetr** [comment]
@carsonperrotti  any update on this issue before closing it ? Thanks

**Comment by carsonperrotti** [comment]
Sorry about that. Was doing some clean up on the issues. I am finishing up the next version that improves how this work and will include instructions in the documentation.

**Comment by carsonperrotti** [comment]
Version 0.2.0 has been released. Check it out.
