### ISSUE TITLE
Project on temporary hold (Please Read)

### ISSUE THREAD

**Issue by carsonperrotti** [carsonperrotti/CNPPopupController#28]
Hi everyone! Thanks for the great feedback and requests. I am very sorry for the delay to the updates with this project. I am transferring to a new company and this has been taking up all of my extra time. I will resume updates as soon as I can. Thanks for your patience.

**Comment by judgetr** [comment]
Hey, good luck in your next company.Do you have any estimation for the next update?

**Comment by carsonperrotti** [comment]
Thank you! I am making the transition on Monday the 9th. I should be able to resume development on my projects by the following weekend.

**Comment by carsonperrotti** [comment]
Version 0.2.0 has been released! Very sorry for the long wait.
