### ISSUE TITLE
CNPPopupButton textlabel color is always white

### ISSUE THREAD

**Issue by jett0423** [carsonperrotti/CNPPopupController#29]
Hello,

I have tried CNPPopupButton in iOS 8. I'm not sure about iOS 7 though.
I've also tried substituting a normal UIButton for it but still no dice.

Thanks in advance for this!

**Comment by carsonperrotti** [comment]
Make sure you are setting the text color correctly. Try this and let me know if that fixes the problem.

```[yourButton setTitleColor:[UIColor colorWithRed:36/255.0 green:71/255.0 blue:113/255.0 alpha:1.0] forState:UIControlStateNormal];```

**Comment by jett0423** [comment]
Ooops! It works now. My bad. Thank you!

**Comment by carsonperrotti** [comment]
Glad I could help. :+1:
