### ISSUE TITLE
Doesn't move above keyboard

### ISSUE THREAD

**Issue by ippily** [carsonperrotti/CNPPopupController#31]
Hi I am using this in my project for an iPad but the problem is that when the keyboard shows up, the pop up doesn't move. Any suggestions on how to fix?

@property (nonatomic, assign) BOOL movesAboveKeyboard;

**Comment by carsonperrotti** [comment]
Thanks for the heads up. I'll fix this with #32 
Going to mark it as a duplicate for now, but it will get resolved with that issue as it's the same bit of code.

**Comment by pjebs** [comment]
Not fixed of ipad running an iphone app.

**Comment by pjebs** [comment]
Not fixed for iphone 5s simualator either.
