### ISSUE TITLE
moveabovekeyboard pushing the popup too far up the screen.

### ISSUE THREAD

**Issue by jsoncylu** [carsonperrotti/CNPPopupController#32]
On both the 5s and 6 screens, enabling the moving above keyboard pushes the popup too far above the screen. is there a way to make it move up less? there's too much of a gap between the top of the keyboard and bottom of the popup.

**Comment by carsonperrotti** [comment]
Thanks for the heads up on this. I'll see if I can improve it.

**Comment by carsonperrotti** [comment]
Fixed in pod version 0.2.2
