### ISSUE TITLE
Platform version 6.0

### ISSUE THREAD

**Issue by nishal** [carsonperrotti/CNPPopupController#34]
Does this work with iOS 6.0? If it does then would you be able to drop the platform version to 6.0 or set deployment target to 6.0? It would be very useful. TIA.

**Comment by carsonperrotti** [comment]
I theory it should. However, I do not have an iOS 6 Device or simulator to test it on to make sure. If you checkout the project and verify that it works on iOS 6, I will lower the version.

**Comment by nishal** [comment]
Sure, will let you know.

**Comment by nishal** [comment]
Tested your code on iOS 6 and all seems good except for the centering issue, so you can drop to iOS 6 in the pod-spec.
