### ISSUE TITLE
Content centering issue

### ISSUE THREAD

**Issue by nishal** [carsonperrotti/CNPPopupController#35]
Thanks for the great code, saved me a lot of time to write my own from scratch, so copied and modified to my needs.

Just thought I'd report this FYI.

I tried one view and multiple views, but seems the items are shifted slightly to the right.

I've tried fixing the method "- (CGSize)calculateContentSizeThatFits:(CGSize)size andUpdateLayout:(BOOL)update" but seems like it is not quiet easily done given the view hierarchy of the views and insets.

**Comment by carsonperrotti** [comment]
Can you post a screenshot of what your content looks like slightly shifted? I want to reproduce this so I can solve it. Thank you.

**Comment by acegreen** [comment]
FYI, on iPad the popup is slightly shifted downwards.

**Comment by GeniusWiki** [comment]
I test in latest code, if the pop only a button, the button can not align to centre.  Just modify like this in sample:
```
    self.popupController = [[CNPPopupController alloc] initWithContents:@[button]];
```
Only I put UIImageView, it works as expected. Is there any thing missing?

**Comment by carsonperrotti** [comment]
Thank you @GeniusWiki for that helpful tip. I will try that out today and see if I can make a fix soon.

**Comment by prsolucoes** [comment]
Same problem:

```
UIWebView *webview = [[UIWebView alloc]initWithFrame:CGRectMake(0, 0, [[UIScreen mainScreen] bounds].size.width - 20, [[UIScreen mainScreen] bounds].size.height - 80)];
webview.backgroundColor = [UIColor whiteColor];
    
CNPPopupController *popupController = [[CNPPopupController alloc] initWithContents:@[webview]];
```

![simulator screen shot jun 30 2016 17 13 17](https://cloud.githubusercontent.com/assets/395096/16502675/f7055c72-3ee5-11e6-879d-f8a48b535866.png)

**Comment by prsolucoes** [comment]
I have solved the problem setting the maxWidth of control. Thanks ppl.
