### ISSUE TITLE
Share & Rate Feature 

### ISSUE THREAD

**Issue by acegreen** [carsonperrotti/CNPPopupController#36]
Feature Suggestions:

1. A share feature 
Propose to add a button that would allow for a share feature where you can define what is to be shared. It would then do sort of what UIActivitiyViewController currently does but in an integrated manner.

2. A rate feature
Similar to a rate feature. I propose we add a button that would allow the user to rate our app. Maybe integrating with SARate. SARate allows you to tap stars within the app first and based on that either takes you to an email or to the AppStore to perform the actual review. This allows you to set a minimum star rating and diverting the user to email communication if the rating it to low. 

Both features should be directly integrated with CNPPopupController 

I’m trying to do the following:

        let shareButton: CNPPopupButton = CNPPopupButton(type: UIButtonType.System)
        shareButton.setTitleColor(UIColor.whiteColor(), forState: UIControlState.Normal)
        shareButton.setTitleColor(UIColor.lightGrayColor(), forState: UIControlState.Highlighted)
        shareButton.titleLabel?.font =  UIFont.boldSystemFontOfSize(20)
        shareButton.setTitle("Share your accomplishment for a reward", forState: UIControlState.Normal)
        shareButton.backgroundColor = UIColor.greenColor()
        shareButton.layer.cornerRadius = 4
        shareButton.addTarget(self, action: "shareWorkout", forControlEvents: UIControlEvents.TouchUpInside)

func shareWorkout() {
        
        let textToShare: String = "Checkout StockSwipe, probably the funnest way to discover stocks on iPad!"
        
        let objectsToShare: NSArray = [textToShare, appURL!]
        
        let excludedActivityTypesArray: NSArray = [
            UIActivityTypePostToWeibo,
            UIActivityTypeAddToReadingList,
            UIActivityTypeAssignToContact,
            UIActivityTypePrint,
            UIActivityTypeSaveToCameraRoll,
            UIActivityTypeAssignToContact,
            UIActivityTypeAirDrop,
        ]
        
        let activityVC = UIActivityViewController(activityItems: objectsToShare as [AnyObject], applicationActivities: nil)
        activityVC.excludedActivityTypes = excludedActivityTypesArray as? [String]
        
        activityVC.popoverPresentationController!.permittedArrowDirections = UIPopoverArrowDirection.Unknown
        
        activityVC.popoverPresentationController!.sourceView = self.view
        activityVC.popoverPresentationController!.sourceRect = CGRectMake(self.view.bounds.width / 2, self.view.bounds.height / 2,0,0)
        
        self.presentViewController(activityVC, animated: true, completion: nil)
        
    }

I would add this as a enhancement feature as most will likely use it

**Comment by carsonperrotti** [comment]
The reason why UIActivityViewController is appearing behind the popup is that the popup is presented as a subview on UIWindow. 

Its typically not suggested by the Interface guidelines to have a share sheet to appear over other popups or action sheets. I would suggest dismissing the popup when your user presses a button, then present the UIActivityViewController. That way you do not have them layered over each other.

**Comment by acegreen** [comment]
Thanks for the response.

I definitely agree with your statement. I was wondering if we can have a more integrated approach. By dismissing first then presenting the UIActivityViewController, we will have it appear in the middle of no where.

I would like to have a share button that present share features within our CNPPopupController 

What do you think of that?

**Comment by carsonperrotti** [comment]
I think that is a bit too specific of a use case for this project. This pod is meant to be generic enough to work for all applications.

I would suggest forking the repo and making modifications to the code to fit your use case.

**Comment by acegreen** [comment]
Ok that's fair. Maybe we can keep the ticket open to see if it gains any traction.

Cheers
Ace
