### ISSUE TITLE
Orientation handling on iOS9 broken

### ISSUE THREAD

**Issue by acegreen** [carsonperrotti/CNPPopupController#37]
I noticed CNPPopupController doesn’t handle orientation properly on iOS9. Work on iOS8 as expected
Issue on both iPhone and iPad running iOS9

First picture is presenting the view in portrait then going to landscape
Second picture is going back to portrait

![simulator screen shot aug 30 2015 10 08 09 pm](https://cloud.githubusercontent.com/assets/10794609/9570917/a6666c24-4f63-11e5-8392-f233ffd4c37b.png)
![simulator screen shot aug 30 2015 10 08 11 pm](https://cloud.githubusercontent.com/assets/10794609/9570918/a67228ca-4f63-11e5-9049-676ce383b6ca.png)

**Comment by carsonperrotti** [comment]
I will test this out.

**Comment by acegreen** [comment]
Great! :+1:

**Comment by carsonperrotti** [comment]
Will push an update for this fix later this evening. Thanks for the heads up about the bug.

**Comment by acegreen** [comment]
Any updates?

**Comment by carsonperrotti** [comment]
Sorry for the delay, I have been busy with client work and have not yet had the time to finish the fix. I will try to get it updated ASAP.

**Comment by wsidell** [comment]
I'm looking forward to the bugfix as well.

**Comment by carsonperrotti** [comment]
Resolved in pod v0.3.0

Thanks for your patience with this issue, it's been busy month.

**Comment by acegreen** [comment]
Confirmed
