### ISSUE TITLE
Feature enhancement: "X" to dismiss CNPPopupController

### ISSUE THREAD

**Issue by acegreen** [carsonperrotti/CNPPopupController#38]
Adding an "X" to dismiss on the top right would take less space and be in line with how Apple handles dismiss overall. currently I need a button which takes space. Taping outside also causes a dismiss but on a 4S with a big PopupControlller, there is no room and its not intuitive.

**Comment by carsonperrotti** [comment]
Again, this falls into the realm of too specific for general use. Most alerts do not have a close 'X' but rather a destructive button. The popup allows you to add custom views yourself or you can fork the repo and customize it to your specific use case.
