### ISSUE TITLE
Different behaviour on UIImage

### ISSUE THREAD

**Issue by nicolasFernandez** [carsonperrotti/CNPPopupController#40]
So, I upgraded from 0.1 to 0.3.1 because for some reason I can't use same version on Swift 2. Well, when I'm trying to present a popup with an image inside of it looks something like this... It's not adjusting to view as you can see on the screenshot. 

![img_0006](https://cloud.githubusercontent.com/assets/3868394/10459503/8703c4e0-71ae-11e5-92fd-90cd847a604a.jpg)

This is my code:

        let promoCodeLabel : UILabel = UILabel.init()
        promoCodeLabel.numberOfLines = 0
        promoCodeLabel.attributedText = promoCode

        let iconImageView = UIImageView(image: UIImage(named: "coupon001_detail"))

        let buttonItemTitle =  NSLocalizedString("COUPON_BTN_TITLE",comment:"")
        let buttonItem: CNPPopupButton = CNPPopupButton.init()
        buttonItem.titleLabel?.attributedText = NSAttributedString(string: buttonItemTitle)
        buttonItem.backgroundColor = ColorStyleUtils.shellYellow.uiColor
        buttonItem.selectionHandler = {(buttonItem) in
            print("SOME ACTION")
        }

        popupController = CNPPopupController.init(contents: [iconImageView, promoCodeLabel, buttonItem])

        let theme = CNPPopupTheme.defaultTheme()

        popupController.theme = theme
        popupController.theme.popupStyle = CNPPopupStyle.Centered
        popupController.delegate = self
        popupController.theme.presentationStyle = CNPPopupPresentationStyle.SlideInFromBottom
        popupController.presentPopupControllerAnimated(true)

**Comment by nicolasFernandez** [comment]
finally solved it by doing this.... 

      let iconImageView = UIImageView()
        iconImageView.contentMode = UIViewContentMode.ScaleAspectFit
        iconImageView.clipsToBounds = true

        let iconImage = UIImage(named: "coupon001_detail")
        iconImageView.image = iconImage

**Comment by carsonperrotti** [comment]
Glad you were able to find a solution. `ScaleAspectFit` is usually a good way to go.
