### ISSUE TITLE
it would be nice to have a method to know if the popup is being presented or not

### ISSUE THREAD

**Issue by agiguere** [carsonperrotti/CNPPopupController#43]
It would be nice to have a method kind of isBeingPresented to know if the popup is currently being presented or not

thanks

**Comment by carsonperrotti** [comment]
You can set that up yourself by using the delegate methods

```
- (void)popupControllerWillPresent:(CNPPopupController *)controller;
- (void)popupControllerDidPresent:(CNPPopupController *)controller;
- (void)popupControllerWillDismiss:(CNPPopupController *)controller;
- (void)popupControllerDidDismiss:(CNPPopupController *)controller;
```

You will now know when it will start to present and when it has been dismissed. 
I hope that helps.
