### ISSUE TITLE
fullscreen mode needs to resize subview at orientation changed.

### ISSUE THREAD

**Issue by GeniusWiki** [carsonperrotti/CNPPopupController#44]
if popup theme is fullscreen mode, when changing orientation,  it is better also resize the content view. I use autoLayout at the pop view.

**Comment by GeniusWiki** [comment]
more detail, I basically add these lines in  orientationChanged:
```
      if (self.theme.popupStyle == CNPPopupStyleFullscreen) {
            [self.popupView setFrame:self.applicationWindow.bounds];
            [self calculateContentSizeThatFits:self.applicationWindow.bounds.size andUpdateLayout:true];
        }
```

I also suggest add an optional delegate method to notification this orientation change, so that the customised pop view can detect this event without need to using NSNotificationCenter again.

**Comment by carsonperrotti** [comment]
I will look into this. Thanks for the suggestion.

**Comment by Neney22** [comment]
Can I use this inside a Spritekit Scene ?

**Comment by carsonperrotti** [comment]
I spent a little time playing with that solution today and could not find that it made any difference. Can you tell me a little more about what content that you are adding and how it adjusts when rotated?

**Comment by carsonperrotti** [comment]
If this is no longer an issue I'm going to close this issue. Feel free to comment if you are still running into issues with your usage of it.
