### ISSUE TITLE
UIAlertController 

### ISSUE THREAD

**Issue by pjebs** [carsonperrotti/CNPPopupController#48]
UIAlertController seems to be behind CNPPopupController.

    UIAlertController* alert = [UIAlertController alertControllerWithTitle:@"My Alert"
                                   message:@"This is an alert."
                                   preferredStyle:UIAlertControllerStyleAlert];
     
    UIAlertAction* defaultAction = [UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault
       handler:^(UIAlertAction * action) {}];
     
    [alert addAction:defaultAction];
    [self presentViewController:alert animated:YES completion:nil];

**Comment by pjebs** [comment]
This is due to the way CNPPopupController operates: It gets the keyWindow, and then puts a `mashView` that is fullscreen to cover it and then puts the `popupview` on top of the mashview.

The UIAlertController requires a UIViewController (`self` above) but it ends up being below.

**Comment by pjebs** [comment]
This seems to work but not sure **how often** it works.

UIViewController *vc = [UIApplication sharedApplication].windows[1].rootViewController;
[vc presentViewController:alert animated:YES completion:nil];

**Comment by carsonperrotti** [comment]
This is correct and is as intended to improve compatibility with older versions of iOS that don't support custom presentation styles or UIAlertController. Why is there a need to present a UIAlertController above a popup? Stacked dialogs sounds a bit messy to me.
