### ISSUE TITLE
Question: Initialize CNPopuoController with a view of other controller

### ISSUE THREAD

**Issue by oferRounds** [carsonperrotti/CNPPopupController#50]
Specifically, I have an instance of UITableViewController which I'd like to present as the content of the popup.
Any idea if this thing could be achieved?

Thanks for this really great component!

**Comment by carsonperrotti** [comment]
Hi there. This isn't really the functionality provided by this control. You should check out [MZFormSheetController]https://github.com/m1entus/MZFormSheetController) which does what you're looking for.

**Comment by oferRounds** [comment]
Cool - thanks!
