### ISSUE TITLE
Content with problem when need keyboard

### ISSUE THREAD

**Issue by prsolucoes** [carsonperrotti/CNPPopupController#53]
Hi,

My popup have only a webview, but when i click on html field, the keyboard appear but too small.

The code:

```
CNPPopupController *popupController = [[CNPPopupController alloc] initWithContents:@[webview]];
    popupController.theme = [CNPPopupTheme defaultTheme];
    popupController.theme.popupStyle = popupStyle;
    popupController.theme.maxPopupWidth = [[UIScreen mainScreen] bounds].size.width - 20;
    popupController.delegate = delegate;
    popupController.theme.cornerRadius = 6.0;
    popupController.theme.popupContentInsets =  UIEdgeInsetsMake(0.0, 0.0, 0.0, 0.0);
    popupController.theme.movesAboveKeyboard = YES; // tried yes and no here
```

The the image.
![simulator screen shot jul 1 2016 15 36 31](https://cloud.githubusercontent.com/assets/395096/16531209/cadd4300-3fa1-11e6-8fde-cc6a3240065f.png)

**Comment by carsonperrotti** [comment]
Are you using the simulator? Press Command + K on your keyboard to bring it up. This is how the simulator typically works.

**Comment by prsolucoes** [comment]
Wow...thansk man...works.
