### ISSUE TITLE
Autolayout constraints for popup content

### ISSUE THREAD

**Issue by dafdafydd** [carsonperrotti/CNPPopupController#56]
Hello,

Thank you very much for this library and all your hard work.

I have a question - are you planning to add support for autolayout constraints to popup content? Do you happen to have an example what the constraints should look like so that the content behaves correctly when orientation changes?

I am attaching a screenshot of what it looks like right now.

<img width="669" alt="zrzut ekranu 2016-08-27 o 09 13 22" src="https://cloud.githubusercontent.com/assets/5732680/18025867/e7b1523e-6c36-11e6-92c0-f7a9fc786b07.png">

**Comment by carsonperrotti** [comment]
I don't have an example using constraints. A lot of people using this library may not want to write the large amount of code required for constraints for each view in the popup so it's likely not something I will consider adding for the time being, unless there is a strong argument to do so.

**Comment by dafdafydd** [comment]
OK, thank you

**Comment by carsonperrotti** [comment]
Going to close this issue. If there's more interest from others to use autolayout, we can discuss and reopen it.
