### ISSUE TITLE
Corner Radius Issue

### ISSUE THREAD

**Issue by pjebs** [carsonperrotti/CNPPopupController#58]
I set the `cornerRadius` to 8 and set `movesAboveKeyboard` to true.

The corner radius works well until...
A UITextView that is inside the popupController makes the keyboard come up.

Then the cornerRadius disappears. Everything else works fine.

**Comment by carsonperrotti** [comment]
Is it possible that the top and bottom of your view are just being clipped by the keyboard and top of the screen? This would hide the corner radius and make it appear as though the corners are now square. 

See this example:
![simulator screen shot sep 15 2016 2 30 49 pm](https://cloud.githubusercontent.com/assets/2063102/18562347/51b69314-7b51-11e6-83f8-4a2665db6c03.png)

**Comment by pjebs** [comment]
![simulator screen shot 16 sep 2016 8 58 22 pm](https://cloud.githubusercontent.com/assets/5377970/18583926/00073c8e-7c51-11e6-84a0-e6b2ca7163cc.png)
![simulator screen shot 16 sep 2016 9 02 21 pm](https://cloud.githubusercontent.com/assets/5377970/18583928/01e84fa2-7c51-11e6-8f00-b8e9b4f83257.png)

**Comment by pjebs** [comment]
I think all you need to do is shen a corner radius is set, also set `clipToBounds`.

**Comment by carsonperrotti** [comment]
Oh I see! I'll try to get that done this weekend.

**Comment by pjebs** [comment]
Closing issue. Not related to your control!.

**Comment by carsonperrotti** [comment]
Thanks for the follow up.
