### ISSUE TITLE
REQUEST: make public

### ISSUE THREAD

**Issue by pjebs** [carsonperrotti/CNPPopupController#59]
Can you please make these public:

Pit inside `CNPPopupController.h:`
```
@property (nonatomic, strong) UIView *maskView;
@property (nonatomic, strong) UIView *popupView;
```

**Comment by pjebs** [comment]
It won't affect your code at all but allows us to modify the view hierarchy to do creative things (or in my case make your control work nicely with another 3rd Party library)

**Comment by carsonperrotti** [comment]
I would suggest making a fork of this library and modifying it to your custom needs for that 3rd party library.
