### ISSUE TITLE
Is it possible two add more than one button?

### ISSUE THREAD

**Issue by jvalerioRidgeRun** [carsonperrotti/CNPPopupController#61]
Hi i was wondering if there is a way to add more than one button for the popups, because when i tried to add more buttons, I only got whitespace.

**Comment by carsonperrotti** [comment]
By modifying the example in the repo, I was able to add multiple buttons. Perhaps it's an issue with your configuration. I would suggest experimenting with the example project and seeing where the difference is. 

![simulator screen shot sep 28 2016 9 50 34 am](https://cloud.githubusercontent.com/assets/2063102/18916069/1c0de996-8561-11e6-9b64-60fda6c79655.png)

**Comment by carsonperrotti** [comment]
Going to close this issue since I have not been able to reproduce your issue and have not heard back.
