### ISSUE TITLE
Presenting 2 PopupController one above another will not dismiss

### ISSUE THREAD

**Issue by rahulvyas** [carsonperrotti/CNPPopupController#62]
Hi,

If we present 2 popup controller at same time one above other we can dismiss the top one but after that we are not able to dismiss other popups.

**Comment by carsonperrotti** [comment]
Unfortunately, this library was not built with the intention of presenting one popup above the other as it is a design pattern that is discouraged in Apple's Interface Guidelines. I would suggest making a fork of the repo and making changes for your custom application.

**Comment by carsonperrotti** [comment]
Going to close this issue since I haven't heard back, and it's out of scope for this library.
