### ISSUE TITLE
DismissController

### ISSUE THREAD

**Issue by sourabhsharmait** [carsonperrotti/CNPPopupController#63]
Touch on backgorund in swift 3 is not working.

I used popview on Tableview may be this is the cause. Please resolve this great repository.

**Comment by carsonperrotti** [comment]
The swift example has already been updated for Swift 3 and touch to dismiss is working there. That leads me to think that it is something with your specific usage. Can you provide some more context or an example of how you are initializing and presenting the controller?

**Comment by sourabhsharmait** [comment]
Issue is resolved. Thanks for your response.

I have declared the popupcontroller locally in a function block so that was the reason it was not working.

Thanks for your response
