### ISSUE TITLE
Support With IQKeyBoardMangager

### ISSUE THREAD

**Issue by sourabhsharmait** [carsonperrotti/CNPPopupController#64]
Not Working with IQKeyBoardMangager. If popup has text field its not going up. in the action sheet style

**Comment by carsonperrotti** [comment]
This library already has its own keyboard avoiding mechanism [see here](https://github.com/carsonperrotti/CNPPopupController/blob/master/CNPPopupController/CNPPopupController.m#L206). Its likely that they two are competing or conflicting. Try disabling IQKeyboardManager before presenting the popup.

**Comment by carsonperrotti** [comment]
I'm going to assume you were able to resolve the problem, and close this issue.

**Comment by vercity** [comment]
It seems that keyboardWillShow method in cnppopup will not be invoked when using iqkeyboardmanager.
