### ISSUE TITLE
Ehancement: Swipe to dismiss.

### ISSUE THREAD

**Issue by YouKnowOJ** [carsonperrotti/CNPPopupController#66]
Is there a way to dismiss the popupController when the user swipes up or down?

**Comment by carsonperrotti** [comment]
I'll consider it, but initially I feel that it's out of scope for this project. The goal is to create a un-opinionated and basic implementation for you to build custom popups your way and not limit or burden anyone with more than they need.

If there's enough interest I'll consider it. For now, I would suggest making a fork of the repo and making the changes for what you have in mind for your project.
