### ISSUE TITLE
Some Theme properties doesn't work

### ISSUE THREAD

**Issue by WinKhantAung** [carsonperrotti/CNPPopupController#71]
Hello...I'm just using your popup and it's all doing well except some theme properties,cornerRadius and movesAboveKeyboard. Can u suggest me sth pls? 
ty

**Comment by carsonperrotti** [comment]
Are you setting any appearance proxies? Example: ```UIView.appearance()...```. Second, are you using IQKeyboard manager or any other keyboard handling library?

**Comment by WinKhantAung** [comment]
Neither Carsonperrotti. But i'm going to use IQKeyboard Mananger. You mean both these two options are not compatible with CNP?

**Comment by anirudhamahale** [comment]
I am also facing the same issue as I am using `textField.becomeFirstResponder()` to get keyboard up, I am also using IQKeyboardManager. It only works if I comment `textField.becomeFirstResponder()`

**Comment by carsonperrotti** [comment]
I've created #74 for compatibility with IQKeyboardManager as it is a different issue than theme properties. 

@WinKhantAung As for theme properties like `cornerRadius`, I will investigate. Have you found a fix? Anything that can help point me in a direction with your particular issue.
