### ISSUE TITLE
Adding border, etc

### ISSUE THREAD

**Issue by iBicha** [carsonperrotti/CNPPopupController#72]
Is there anyway (that i'm missing) to add a border to the view? as far as i can tell, i need to access popupView (to set it's layer.borderWidth and color) but that can't be done.

For now, i'm doing an init with content, then getting the popupView with the superview of one of my views added. It works, but it's a bit of a hack.

I'm only suggesting to make the popupView open, so it's possible to further customize it. (maybe the maskView too? that's to discuss)

**Comment by carsonperrotti** [comment]
I would also gladly accept a PR for this too to extend the theme.
