### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by prsolucoes** [carsonperrotti/CNPPopupController#81]
Hi,

I use it in my project using cocoapods, but i need use in my new project that use carthage.

Can you add carthage support please?

Thanks.

**Comment by carsonperrotti** [comment]
I'll check it out. Thanks for the suggestion.

**Comment by prsolucoes** [comment]
Hi,

This is the day to integrate it into my new project. Can you add carthage support to i use it here?

Thanks.
