### ISSUE TITLE
Look into Swift usage

### ISSUE THREAD

**Issue by carsonperrotti** [carsonperrotti/CNPPopupController#9]
Look into using selectionHandler block in swift. Possible issue.

**Comment by acegreen** [comment]
Did you figure this out?

right now I add a target to a function that does the dismiss. 

How do you translate this into Swift?

    button.selectionHandler = ^(CNPPopupButton *button){
        [self.popupController dismissPopupControllerAnimated:YES];
        NSLog(@"Block for button: %@", button.titleLabel.text);
    };

**Comment by carsonperrotti** [comment]
You should just be able to set it with 
```
button.selectionHandler = {
    button in
    // do something
}
```
